@api = http://localhost:5000/api
@grpcApi = http://localhost:50000/battle.Battle
@heroId = 6550dca5-1334-440e-81e7-2e495db2b0f9
@enemyId = bcc3ecb7-6680-404a-8b12-5ade67d93c5b
@mapId = 2c70e345-024f-4b12-b1ff-11f33ff40fdb
@email = tester@rpg-game.com
@password = PAsW0Rd!123
@userId = 68945a59-bb5f-48d0-a855-4a8b679c8e74
@playerId = c37501ec-8f21-4af7-9668-ffc3f4528d32
@refreshToken = npdRGElAgPZxFbEBqvN2DclhzwWBvPALkOQ6LZ
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNTM3MzVlMC0xYzY3LTRlMWQtYWI0NC03NTQ4MGU5NTkyZDUiLCJ1bmlxdWVfbmFtZSI6IjI1MzczNWUwLTFjNjctNGUxZC1hYjQ0LTc1NDgwZTk1OTJkNSIsImVtYWlsIjoidGVzdGVyQHJwZy1nYW1lLmNvbSIsImp0aSI6ImU5ZDNlYWIwLTk0OWUtNDM5Yi1iZTJkLTJjODA2NDc4ZTg3NCIsImlhdCI6IjE2Njg3NjU1MzUxODYiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsIm5iZiI6MTY2ODc2NTUzNSwiZXhwIjoxNjY4NzY5MTM1LCJpc3MiOiJycGctZ2FtZSJ9.r9JX138tY7n33ocg61spjrg21Dd3jL-mmAVBuzgXFwA

###
GET {{api}}

###
POST {{api}}/heroes
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "heroName": "Warrior",
    "health": {
        "value": 10,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 3
        }
    },
    "attack": {
        "value": 5,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 4
        }
    },
    "healLvl": {
        "value": 2,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 2
        }
    },
    "baseRequiredExperience": {
        "value": 1000,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 20
        }
    },
    "skills": [
        {
            "name": "Cyclon",
            "baseAttack": 10,
            "increasingState": {
                "strategyIncreasing": "PERCENTAGE",
                "value": 5
            }
        }
    ]
}

###
GET {{api}}/heroes/{{heroId}}
Authorization: Bearer {{accessToken}}

###
PUT {{api}}/heroes/{{heroId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "heroName": "Warrior#1",
    "health": {
        "value": 10,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 3
        }
    },
    "attack": {
        "value": 5,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 4
        }
    },
    "healLvl": {
        "value": 2,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 2
        }
    },
    "baseRequiredExperience": {
        "value": 1000,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 20
        }
    },
    "skills": [
        {
            "id": "7b346a99-785e-4302-9b39-1cf0cda06f7b",
            "name": "Cyclon",
            "baseAttack": 10,
            "increasingState": {
                "strategyIncreasing": "PERCENTAGE",
                "value": 5
            }
        }
    ]
}

###
GET {{api}}/heroes/{{heroId}}
Authorization: Bearer {{accessToken}}

###
GET {{api}}/heroes
Authorization: Bearer {{accessToken}}

###
DELETE {{api}}/heroes/{{heroId}}
Authorization: Bearer {{accessToken}}

###
GET {{api}}/enemies
Authorization: Bearer {{accessToken}}

###
POST {{api}}/enemies
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "enemyName": "Knight",
    "baseAttack": {
        "value": 2,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 3
        }
    },
    "baseHealth": {
        "value": 10,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 3
        }
    },
    "baseHealLvl": {
        "value": 2,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 2
        }
    },
    "experience": {
        "value": 100,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 10
        }
    },
    "difficulty": "EASY",
    "category": "Archer",
    "skills": [
        {
            "name": "damage",
            "baseAttack": 4,
            "probability": 20,
            "increasingState": {
                "strategyIncreasing": "PERCENTAGE",
                "value": 5
            }
        }
    ]
}

###
GET {{api}}/enemies/{{enemyId}}
Authorization: Bearer {{accessToken}}

###
PUT {{api}}/enemies/{{enemyId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "enemyName": "Knight#1",
    "baseAttack": {
        "value": 2,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 3
        }
    },
    "baseHealth": {
        "value": 10,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 3
        }
    },
    "baseHealLvl": {
        "value": 2,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 2
        }
    },
    "experience": {
        "value": 100,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 10
        }
    },
    "difficulty": "EASY",
    "category": "Knight",
    "skills": [
        {
            "name": "damage",
            "baseAttack": 4,
            "probability": 20,
            "increasingState": {
                "strategyIncreasing": "PERCENTAGE",
                "value": 5
            }
        }
    ]
}

###
DELETE {{api}}/enemies/{{enemyId}}
Authorization: Bearer {{accessToken}}

###
GET {{api}}/maps
Authorization: Bearer {{accessToken}}

###
POST {{api}}/maps
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Triv",
    "difficulty": "EASY",
    "enemies": [
        {
            "enemyId": "{{enemyId}}",
            "quantity": 2
        }
    ]
}

###
GET {{api}}/maps/{{mapId}}
Authorization: Bearer {{accessToken}}

###
PUT {{api}}/maps/{{mapId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Trivi",
    "difficulty": "EASY",
    "enemies": [
        {
            "enemyId": "{{enemyId}}",
            "quantity": 2
        }
    ]
}

###
POST {{api}}/account/sign-up
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}",
    "role": "admin"
}

###
POST {{api}}/account/sign-in
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###
POST {{api}}/refresh-tokens/use
Content-Type: application/json

{
    "token": "{{refreshToken}}"
}

###
GET {{api}}/maps/{{mapId}}
Authorization: Bearer {{accessToken}}

###
GET {{api}}/players
Authorization: Bearer {{accessToken}}

###
POST {{api}}/players
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "DKP",
    "heroId": "{{heroId}}",
    "userId": "{{userId}}"
}

###
GET {{api}}/players/{{playerId}}
Authorization: Bearer {{accessToken}}

###
PUT {{api}}/players/{{playerId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "id": "{{playerId}}",
    "name": "Tester",
    "currentExp": 1,
    "requiredExp": 1000,
    "heroAttack": 15,
    "heroHealth": 30,
    "heroHealLvl": 7,
    "heroSkills": [
        {
            "skillId": "7b346a99-785e-4302-9b39-1cf0cda06f7b",
            "attack": 28
        }
    ]
}

###
DELETE {{api}}/players/{{playerId}}
Authorization: Bearer {{accessToken}}

###
POST {{grpcApi}}/PrepareBattle
Authorization: Bearer {{accessToken}}
Content-Type: application/grpc-web-text

AAAAAAA=