@api = http://localhost:5000/api
@heroId = 6550dca5-1334-440e-81e7-2e495db2b0f9
@enemyId = bcc3ecb7-6680-404a-8b12-5ade67d93c5b
@mapId = 2c70e345-024f-4b12-b1ff-11f33ff40fdb
@email = tester@rpg-game.com
@password = PAsW0Rd!123
@userId = 68945a59-bb5f-48d0-a855-4a8b679c8e74
@playerId = c37501ec-8f21-4af7-9668-ffc3f4528d32

###
GET {{api}}

###
POST {{api}}/heroes
Content-Type: application/json

{
    "heroName": "Warrior",
    "health": {
        "value": 10,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 3
        }
    },
    "attack": {
        "value": 5,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 4
        }
    },
    "healLvl": {
        "value": 2,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 2
        }
    },
    "baseRequiredExperience": {
        "value": 1000,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 20
        }
    },
    "skills": [
        {
            "name": "Cyclon",
            "baseAttack": 10,
            "increasingState": {
                "strategyIncreasing": "PERCENTAGE",
                "value": 5
            }
        }
    ]
}

###
GET {{api}}/heroes/{{heroId}}

###
PUT {{api}}/heroes/{{heroId}}
Content-Type: application/json

{
    "heroName": "Warrior#1",
    "health": {
        "value": 10,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 3
        }
    },
    "attack": {
        "value": 5,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 4
        }
    },
    "healLvl": {
        "value": 2,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 2
        }
    },
    "baseRequiredExperience": {
        "value": 1000,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 20
        }
    },
    "skills": [
        {
            "id": "7b346a99-785e-4302-9b39-1cf0cda06f7b",
            "name": "Cyclon",
            "baseAttack": 10,
            "increasingState": {
                "strategyIncreasing": "PERCENTAGE",
                "value": 5
            }
        }
    ]
}

###
GET {{api}}/heroes/{{heroId}}

###
GET {{api}}/heroes

###
DELETE {{api}}/heroes/{{heroId}}

###
GET {{api}}/enemies

###
POST {{api}}/enemies
Content-Type: application/json

{
    "enemyName": "Knight",
    "baseAttack": {
        "value": 2,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 3
        }
    },
    "baseHealth": {
        "value": 10,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 3
        }
    },
    "baseHealLvl": {
        "value": 2,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 2
        }
    },
    "experience": {
        "value": 100,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 10
        }
    },
    "difficulty": "EASY",
    "category": "Archer",
    "skills": [
        {
            "name": "damage",
            "baseAttack": 4,
            "probability": 20,
            "increasingState": {
                "strategyIncreasing": "PERCENTAGE",
                "value": 5
            }
        }
    ]
}

###
GET {{api}}/enemies/{{enemyId}}

###
PUT {{api}}/enemies/{{enemyId}}
Content-Type: application/json

{
    "enemyName": "Knight#1",
    "baseAttack": {
        "value": 2,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 3
        }
    },
    "baseHealth": {
        "value": 10,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 3
        }
    },
    "baseHealLvl": {
        "value": 2,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 2
        }
    },
    "experience": {
        "value": 100,
        "increasingState": {
            "strategyIncreasing": "PERCENTAGE",
            "value": 10
        }
    },
    "difficulty": "EASY",
    "category": "Knight",
    "skills": [
        {
            "name": "damage",
            "baseAttack": 4,
            "probability": 20,
            "increasingState": {
                "strategyIncreasing": "PERCENTAGE",
                "value": 5
            }
        }
    ]
}

###
DELETE {{api}}/enemies/{{enemyId}}

###
GET {{api}}/maps

###
POST {{api}}/maps
Content-Type: application/json

{
    "name": "Triv",
    "difficulty": "EASY",
    "enemies": [
        {
            "enemyId": "{{enemyId}}",
            "quantity": 2
        }
    ]
}

###
GET {{api}}/maps/{{mapId}}

###
PUT {{api}}/maps/{{mapId}}
Content-Type: application/json

{
    "name": "Trivi",
    "difficulty": "EASY",
    "enemies": [
        {
            "enemyId": "{{enemyId}}",
            "quantity": 2
        }
    ]
}

###
POST {{api}}/account
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}",
    "role": "user"
}

###
POST {{api}}/account/me
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###
GET {{api}}/maps/{{mapId}}

###
GET {{api}}/players

###
POST {{api}}/players
Content-Type: application/json

{
    "name": "DKP",
    "heroId": "{{heroId}}",
    "userId": "{{userId}}"
}

###
GET {{api}}/players/{{playerId}}

###
PUT {{api}}/players/{{playerId}}
Content-Type: application/json

{
    "id": "{{playerId}}",
    "name": "Tester",
    "currentExp": 1,
    "requiredExp": 1000,
    "heroAttack": 15,
    "heroHealth": 30,
    "heroHealLvl": 7,
    "heroSkills": [
        {
            "skillId": "7b346a99-785e-4302-9b39-1cf0cda06f7b",
            "attack": 28
        }
    ]
}

###
DELETE {{api}}/players/{{playerId}}